# Settings
url: https://dawn-cph.github.io/dja/
baseurl: /dja
title: DJA
tagline: The DAWN JWST Archive
repository: dawn-cph/dja
description: The DAWN JWST Archive, Science-ready public JWST data products

bannerTitle: The DAWN JWST Archive
bannerTagline: Science-ready public JWST data products
bannerDescription: The <a href="https://cosmicdawn.dk/"> Cosmic Dawn Center </a> is involved in a number of James Webb Space Telescope (JWST) surveys, but the public data can also be thought of as one comprehensive survey. The DAWN JWST Archive (DJA) is a repository of public JWST galaxy data, reduced with <a href="https://github.com/gbrammer/grizli"> grizli </a> and <a href="https://github.com/gbrammer/msaexp"> msaexp </a>, and released for use by anyone.
bannerImage: images/dja_logo.png
bannerButton: true
bannerButtonLink: about/summary

contactTagline: For DJA questions, please use the <a href="https://github.com/dawn-cph/dja/discussions"> Discussions </a> or <a href="https://github.com/dawn-cph/dja/issues"> Issues </a> functionality on the <a href="https://github.com/dawn-cph/dja"> repository page</a>.<br> <br> For <a href="https://github.com/gbrammer/grizli/issues"> grizli </a> or <a href="https://github.com/gbrammer/msaexp/issues"> msaexp </a> software questions or problems, please file an <i>Issue</i> on the respective GitHub repository pages.
copyright: 2023 Cosmic Dawn Center

# Contact

email:
phone:
address: <a href="https://cosmicdawn.dk/" /> Cosmic Dawn Center </a> <br /> Niels Bohr Institute <br /> University of Copenhagen <br /> Jagtvej 128, 2200 KÃ¸benhavn N
github: dawn-cph
twitter: DAWNCopenhagen
facebook: cosmicdawncenter
linkedin: the-cosmic-dawn-center
instagram: 
snapchat: 

# Pagination
paginate: 4
permalink: /blog/:year/:month/:day/:title/
paginate_path: /blog/page:num/

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
sass:
  sass_dir: assets/sass

# collections:
#   datasets:
#     output: true
#     permalink: /datasets/:path/
#     sort_by: order_number
      
# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji
    - jekyll-feed

feed:
  icon: images/dja_logo_square.png
