# Settings
url: https://dawn-cph.github.io/web
baseurl: https://dawn-cph.github.io/web
title: DAWN-CPH
tagline: by HTML5 UP
bannerTitle: "Hi, Iâ€™m Editorial<br />by HTML5 UP"
bannerTagline: A free and fully responsive site template
bannerDescription: Aenean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
bannerImage: images/pic10.jpg
bannerButton: true
bannerButtonLink: index.html
contactTagline: Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
copyright: Untitled

# Featurette
featuretteTitle: Erat lacinia
featuretteFirstHighlight: Portitor ullamcorper
featuretteFirstTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
featuretteFirstIcon: icon fa-diamond
featuretteSecondHighlight: Sapien veroeros
featuretteSecondTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
featuretteSecondIcon: icon fa-paper-plane
featuretteThirdHighlight: Quam lorem ipsum
featuretteThirdTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
featuretteThirdIcon: icon fa-rocket
featuretteFourthHighlight: Sed magna finibus
featuretteFourthTagline: Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.
featuretteFourthIcon: icon fa-signal

# Contact
email: information@untitled.tld
phone: (000) 000-0000
address: "1234 Somewhere Road #8254<br />Nashville, TN 00000-0000"
twitter: username
facebook: username
instagram: username
snapchat: username
github: username
